### ISSUE TITLE
ContextMenu.close() does not work also contextmenu.element.childElementCount never becomes zero

### ISSUE THREAD

**Issue by depandey** [jonataswalker/ol-contextmenu#119]
I have modified the fiddle created by you and created a new one here [jsfiddle](https://jsfiddle.net/mppxr5jf/).

below is the code with the change, I have marked the lines which I have changed.

`contextmenu.on('open', function (evt) {
  var feature =	map.forEachFeatureAtPixel(evt.pixel, ft => ft);
  
  if (feature && feature.get('type') === 'removable') {
    contextmenu.clear();
    removeMarkerItem.data = { marker: feature };
    contextmenu.push(removeMarkerItem);
  } else {
    contextmenu.clear();
    contextmenu.extend(contextmenu_items);
    contextmenu.extend(contextmenu.getDefaultItems());
  }
  contextmenu.clear(); //added this line
  contextmenu.close(); ////added this line
});`

for the second issue. after calling contextmenu.clear() still contextmenu.element.childElementCount is showing as 1.

ol3-contextmenu - v2.4.1

**Comment by jonataswalker** [comment]
I don't understand the logic here.

**Comment by depandey** [comment]
The two lines which i have inserted is just an over simplified version of
our code. My aim by putting those two lines together is to show that even
though the context menu is cleared and then when we call close on context
menu it is still displayed. And even after we call clear on context menu
still the childElementCount is equal to 1. Let me know if this still sounds
confusing
