### ISSUE TITLE
Open menu on touch device

### ISSUE THREAD

**Issue by SFPink** [jonataswalker/ol-contextmenu#128]
Is there a way to open the context menu on a touch device? (perhaps by holding down for a long period) or does this need implemented manually?

Great component by the way.

Regards

**Comment by jonataswalker** [comment]
Let's do it. Hold on.

**Comment by SFPink** [comment]
I haven't tried anything yet, I was just checking before I started trying to implement something.

Click to open in my case won't work as the map has other click events. I will do a bit of research see if I can come up with anything for a long click, I've seen others timing between mousedown and mouseup to determine if it was a long click so perhaps something similar.

**Comment by huntw999** [comment]
i am able to get context menu with long tap on android - it does not work the same way on iphone 
i have done a fair amount of work on looking at this problem - i will report back when i get a clear solution

**Comment by gesrt** [comment]
I found a temporary solution for touch devices. That is, you can simulate the right click event with hammerjs. To be more specific,
I use the long press function of hammers to get the source event, and then pass it to contextmenu via dispatchEvent.

**Comment by jonataswalker** [comment]
Glad to hear. May you share a fiddle with your solution? Others can benefit.

**Comment by gesrt** [comment]
There is some problem in map dragging while using hammerjs, I used touch eventlistener instead.
`
var timer, touch_x, touch_y;
var touchduration = 500;
var threshold = 9
function touchstart(e) {
	timer = setTimeout(() => {
		if((!touch_x && !touch_y ) ||
		   (Math.abs(touch_x - e.changedTouches[0].clientX) <= threshold &&
			Math.abs(touch_y - e.changedTouches[0].clientY) <= threshold ))
				onlongtouch(e)
	}, touchduration); 
}

function touchmove(e) {
	touch_x = e.changedTouches[0].clientX
	touch_y = e.changedTouches[0].clientY
}

function touchend() {
	if (timer){
		clearTimeout(timer)
		touch_x = touch_y = 0
	}
}

var onlongtouch = (e) => { 
	let ev = new MouseEvent('contextmenu', {
		clientX: e.changedTouches[0].clientX,
		clientY: e.changedTouches[0].clientY,
	});
	this.map.getViewport().dispatchEvent(ev);
	e.preventDefault();
};

this.map.getViewport().addEventListener("touchstart", touchstart, false)
this.map.getViewport().addEventListener("touchend", touchend, false)
this.map.getViewport().addEventListener("touchmove", touchmove, false)
`

**Comment by gesrt** [comment]
There is some problem in map dragging while using hammerjs, I used touch eventlistener instead.


	var timer, touch_x, touch_y
	var touchduration = 500
	var threshold = 9

	function touchstart(e) {
		timer = setTimeout(() => {
			if((!touch_x && !touch_y ) ||
			   (Math.abs(touch_x - e.changedTouches[0].clientX) <= threshold &&
				Math.abs(touch_y - e.changedTouches[0].clientY) <= threshold ))
					onlongtouch(e)
		}, touchduration); 
	}

	function touchmove(e) {
		touch_x = e.changedTouches[0].clientX
		touch_y = e.changedTouches[0].clientY
	}

	function touchend() {
		if (timer){
			clearTimeout(timer)
			touch_x = touch_y = 0
		}
	}

	var onlongtouch = (e) => { 
		let ev = new MouseEvent('contextmenu', {
			clientX: e.changedTouches[0].clientX,
			clientY: e.changedTouches[0].clientY,
		});
		this.map.getViewport().dispatchEvent(ev)
		e.preventDefault()
	};

	this.map.getViewport().addEventListener("touchstart", touchstart, false)
	this.map.getViewport().addEventListener("touchend", touchend, false)
	this.map.getViewport().addEventListener("touchmove", touchmove, false)

**Comment by pelord** [comment]
any update to have this in ios built in?
