### ISSUE TITLE
Option to use Font Awesome instead of icons

### ISSUE THREAD

**Issue by StewartBellamy** [jonataswalker/ol-contextmenu#129]
Hi Jonatas

First off I want to say what a useful plugin this, thanks for making it available.

I have a small feature request.  It would be very handy to able to use FontAwesome (or Glyphicons) as well as /instead of icons.  So something like:
```
                {
                    text: 'Add a Marker',
                    iconClass: 'fa fa-map-marker' ,                   
                    callback: marker
                },
```

Stewart

**Comment by jonataswalker** [comment]
Hi @StewartBellamy 

There is already `classname`.

```javascript
{
  text: 'Foo',
  classname: 'fa fa-map-marker'
}
```

**Comment by StewartBellamy** [comment]
Ok, thanks I'll give it a go.

**Comment by jonataswalker** [comment]
If this is not enough, just ping me.

**Comment by StewartBellamy** [comment]
I ended up just adding the html to the text property.

`text: '<i class="fa fa-crosshairs" aria-hidden="true"></i>Center map here',`

![image](https://user-images.githubusercontent.com/10956017/34565056-4bd85ff0-f151-11e7-9426-2d8a234d381d.png)

I have one small issue, which might be in my control.  I have info popups with links in, when you right click on the link to open in new tab it triggers the context menu.

**Comment by jonataswalker** [comment]
Hmmm, this is really annoying. Would you mind to open a separate ticket for this issue?
