### ISSUE TITLE
Preventing the default browser RightClick context menu from displaying

### ISSUE THREAD

**Issue by depandey** [jonataswalker/ol-contextmenu#133]
When I disable to context menu in the 'beforeopen' event then default browser context menu opens. is there any way to stop it from opening.
here is a [https://jsfiddle.net/tzq4s6s2/](jsFiddle)
To test it, 
1. right click and click on 'Add a marker'
2, and then click on the added marker again.
now, you will see that the default browser context menu open. 
I don't want this to happen. can you tell me how to do that ?

Following code works by previnting default browser context menu from displaying. 
`  document.getElementById('mapDiv').oncontextmenu = function(e){
      e = e?e:window.event;
      if (e.preventDefault) e.preventDefault(); // For non-IE browsers.
      else return false; // For IE browsers.
     };`

**Comment by jonataswalker** [comment]
You've found the solution, right? Can this ticket be closed?
