### ISSUE TITLE
ol-contextmenu does not seem to work with Edge and IE11 navigators

### ISSUE THREAD

**Issue by ogo-adp** [jonataswalker/ol-contextmenu#139]
To reproduce :
- try the demo on start page of this project
- right click four times to make the menu appear. It does work
- on fifth time the menu will not appear and you will get an exception in console (HierarchyRequestError on Edge and NotFoundError on IE11)
- any further attempt will trigger the exception
 
Reproduced on Fall Creators Update and April Update Windows versions.

Seems like the bug is related to DOM manipulation in removeMenuEntry()

removeMenuEntry(index) {
    const element = find('#' + index, this.container.firstChild);
    element && this.container.firstChild.removeChild(element);
    delete this.Base.Internal.items[index];
}

After call of find, element is found by Id, but is not a child of this.container.firstChild -> exception

If I make this mod :  element && element.parentNode ===this.container.firstChild && this.container.firstChild.removeChild(element); then it works again (but it is probably not a proper fix)

**Comment by flyfishMT** [comment]
Hi @jonataswalker, If this is a good fix could @ogo-adp submit a PR with it? I am fighting this issue too. Thanks

**Comment by jonataswalker** [comment]
Hi @flyfishMT and @ogo-adp, linux user here, not easy for me to have this browser, please submit a PR.

**Comment by ohmytrance** [comment]
ie 11 right click about 10 times occured error
