### ISSUE TITLE
TypeScript definition file

### ISSUE THREAD

**Issue by flyfishMT** [jonataswalker/ol-contextmenu#140]
Hello, I use your library with a TypeScript project so I had to create a simple TypeScript definition file.  Any interest in it? I could submit you a PR with it or I could submit it to the definitelytyped project so it is available in npm @types organization.  Here is the best practices: [https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

**Comment by BobbyT** [comment]
please submit your work at @types organization

**Comment by jonataswalker** [comment]
Well, I don't a real benefit for now. Thank you @flyfishMT

**Comment by MaticDiba** [comment]
@flyfishMT could you share the type defintion?

**Comment by flyfishMT** [comment]
@MaticDiba unfortunately I no longer have access to the source, sorry!
