### ISSUE TITLE
classname not set for item that is a submenu

### ISSUE THREAD

**Issue by jcachat** [jonataswalker/ol-contextmenu#148]
If I have an item that is a submenu, the "classname" value is not preserved.  The class that is produced on the element is always " ol-ctx-menu-submenu" (also notice the leading space).

Just from looking at the code, I think the problem is in html.js in the addMenuItem method:

This:
`item.classname = item.classname.length
          ? ' ' + CLASSNAME.submenu
          : CLASSNAME.submenu;`

should have "+=" like this:
`item.classname += item.classname.length
          ? ' ' + CLASSNAME.submenu
          : CLASSNAME.submenu;`

**Comment by jonataswalker** [comment]
@jcachat are you able to provide a PR?

**Comment by jonataswalker** [comment]
Should be solved with #219
