### ISSUE TITLE
Context menu does not close correctly with OL 5.2.0

### ISSUE THREAD

**Issue by cplasse** [jonataswalker/ol-contextmenu#151]
After upgrade from Openlayers 5.1.3 to 5.2.0, context menu opens correctly but it does not close automatically after a click anywhere out of the menu in the map

**Comment by illsio** [comment]
Could you post a fiddle?

**Comment by Johanneshn** [comment]
I'm having the same problem. The example jsfiddle updated to Openlayers 5.2.0
https://jsfiddle.net/ooxs1w5d/621/

**Comment by jonataswalker** [comment]
Hey guys, which `ol-contextmenu` version are you using?

@Johanneshn  your fiddle works fine with ol@4.5 ... https://unpkg.com/openlayers/

**Comment by cplasse** [comment]
I am using OL 5.2.0 with ol-contextmenu 3.3.0

**Comment by jonataswalker** [comment]
Ok @cplasse I'll have to find some time to make it work. Or anyone else can handle this?

**Comment by zicla** [comment]
I have encounter the same problem. OL 5.2.0 with ol-contextmenu 3.3.0

**Comment by SFPink** [comment]
Would be great if the PR was accepted as I've the same issue.

**Comment by jonataswalker** [comment]
Sorry this long delay guys, I'll release a new version with these fixes soon (I'll try tonight).

**Comment by alsaleem00** [comment]
thanks

**Comment by paultucker04** [comment]
I also have this issue

**Comment by joshferrell** [comment]
@jonataswalker it looks like there's [a pr to fix this issue](https://github.com/jonataswalker/ol-contextmenu/pull/156). Is that pr ready for merge?

**Comment by jonataswalker** [comment]
Fixed by #156, folks, I have no words to justify this delay. One more time, I'm sorry. Will release a new version today.
