### ISSUE TITLE
For 'ol-contextmenu' the 'ol/control' differs in casing

### ISSUE THREAD

**Issue by StijnVandermeulen1** [jonataswalker/ol-contextmenu#154]
I have the following warning when importing ol-contextmenu:

> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

at line 9 in ol-contextmenu/src/base.js:  

`export default class Base extends Control {`

I think should be:

`export default class Base extends control {`

To be compatible with all other control classes of openlayers.

Kind regards,
Stijn Vandermeulen

**Comment by StijnVandermeulen1** [comment]
Any update on this? This is a problem since we created a npm package from our project and when we install it we get 'ol/control/Control dependency not found'. (should be ol/control/control)

**Comment by jonataswalker** [comment]
Should be solved with #219
