### ISSUE TITLE
contextmenu is not defined 

### ISSUE THREAD

**Issue by Panchashila** [jonataswalker/ol-contextmenu#155]
hello,
i am using contextmenu in my angular 6 project and ol version is 5.2.0 and 
added contextmenu css and js in index.html of angular app 
 i am getting below error

////////////////////////////////////////////////////////////////////////////////
1)  Uncaught TypeError: **Cannot read property 'control' of undefined**
    at ol-contextmenu.js:7
    at ol-contextmenu.js:7
(anonymous) @ ol-contextmenu.js:7
(anonymous) @ ol-contextmenu.js:7
****
2)
AppComponent.html:3 ERROR ReferenceError: **contextmenu is not defined**
    at MapComponent.push../src/app/map/map.component.ts.MapComponent.ngOnInit (map.component.ts:107)
    at checkAndUpdateDirectiveInline (core.js:9250)
    at checkAndUpdateNodeInline (core.js:10514)
    at checkAndUpdateNode (core.js:10476)
    at debugCheckAndUpdateNode (core.js:11109)
    at debugCheckDirectivesFn (core.js:11069)
    at Object.eval [as updateDirectives] (AppComponent.html:4)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11061)
    at checkAndUpdateView (core.js:10458)
    at callViewAction (core.js:10699)
View_AppComponent_0 @ AppComponent.html:3
proxyClass @ compiler.js:10168
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:11313
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1719
(anonymous) @ core.js:4588
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:3783
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4588
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent @ core.js:4615
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap @ core.js:4557
(anonymous) @ core.js:4358
push../node_modules/@angular/core/fesm5/core.js.PlatformRef._moduleDoBootstrap @ core.js:4358
(anonymous) @ core.js:4324
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3824
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:3815
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:4353
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:76
0 @ main.ts:12
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1
AppComponent.html:3 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…}}

**Comment by ezriYerushalmi** [comment]
Same issue, there is any solution?
@Panchashila

**Comment by RudyMeijer** [comment]
Same issue here.
The context menu is working fine. During pageload index.js an error is displayed.
![image](https://user-images.githubusercontent.com/17112368/56028136-c7d88e80-5d17-11e9-9f4d-a8a1c1d50d5e.png)

The property **control** cannot be read because **ol** is undefined in line 7 of ol-contextmenu.js
t.**ol**.control.Control
![image](https://user-images.githubusercontent.com/17112368/56028556-b479f300-5d18-11e9-886d-5cd4041d1046.png)

**Comment by jonataswalker** [comment]
Should be solved with #219

See [examples](https://github.com/jonataswalker/ol-contextmenu/tree/master/examples)
