### ISSUE TITLE
Jsfiddle is broken and old

### ISSUE THREAD

**Issue by 0trenixjetix** [jonataswalker/ol-contextmenu#157]
I am trying to use the jsfiddle but it's not working anymore because of the ol-contextmenu code not being available.
I tried to update it myself but the last versions of openlayers and ol-contextmenu have the error of ol/control/Control of another issue. 
I got myself a ContextMenu not defined.
[I forked the fiddle with the new software to speed up your work](https://jsfiddle.net/gbsLyx4r/)

**Comment by jonataswalker** [comment]
Fiddle fixed, thanks for reporting.

https://jsfiddle.net/jonataswalker/ooxs1w5d/
