### ISSUE TITLE
Callback function fires only first time

### ISSUE THREAD

**Issue by vfonsecaz** [jonataswalker/ol-contextmenu#165]
Using openlayers v.4.6.5
ol-contextmenu  v.3.3.1

Each menu item callback gets fired only the first time it's called.

fiddle
[https://jsfiddle.net/vfonsecaz/L7ry80gm/4/](https://jsfiddle.net/vfonsecaz/L7ry80gm/4/)

Happened to anyone?

**Comment by vangoo** [comment]
I change ol-contextmenu.js  setItemListener  function like : 

`setItemListener = function(t, e) {
        var n, i = this;
        t && "function" == typeof this.items[e].callback && (n = this.items[e].callback,
        t.addEventListener("click", function(t) {
            t.preventDefault();
            var s = {
                coordinate: i.getCoordinateClicked(),
                data: i.items[e].data || null
            };
            i.closeMenu(),
            n(s, i.map);
        }));
    }`

**Comment by vfonsecaz** [comment]
So you removed the statusClick variable.
I can confirm it's working now.

thanks

ol-contextmenu-debug.js

`   
 Internal.prototype.setItemListener = function setItemListener (li, index) {
        var this_ = this;
        if (li && typeof this.items[index].callback === 'function') {
            (function (callback) {
                li.addEventListener(
                    'click',
                    function (evt) {
                        evt.preventDefault();

                        var obj = {
                            coordinate: this_.getCoordinateClicked(),
                            data: this_.items[index].data || null,
                        };
                        this_.closeMenu();
                        callback(obj, this_.map);
                    },
                    false
                );
            })(this.items[index].callback);
        }
    };`

**Comment by martinmcneela** [comment]
jonataswalker is there any chance of getting this PR merged in? I can see the tests are failing to run, but not sure how/if I can help to fix it.

**Comment by annasimoniaine** [comment]
All checks seem to have passed now and there are no conflicts, so it would be great if this could be merged

**Comment by angelocavallet** [comment]
My bad, it's happened because #153
