### ISSUE TITLE
Menu shows up at left upper corner after page load in OL 6.1.0

### ISSUE THREAD

**Issue by lamaux** [jonataswalker/ol-contextmenu#169]
In OpenLayers 6.1.0, ol-contextmenu shows up at map's upper left corner after page load.
see https://jsfiddle.net/m8t654b2/

**Comment by jonataswalker** [comment]
Are you able to provide a fix?

**Comment by lamaux** [comment]
> 
> 
> Are you able to provide a fix?

I only found a workaround by calling `contextmenu.close()` at the end of page load

**Comment by rinaldofaria** [comment]
> > Are you able to provide a fix?
> 
> I only found a workaround by calling `contextmenu.close()` at the end of page load

Yeah! It's do word fine instead of be named "workaround". (lol)

**Comment by rinaldofaria** [comment]
But I think it's happen 'cos the ol.inherits that was deprecated and was removed on version 6.x.x.

**Comment by lamaux** [comment]
just noticed that #164 will solve this issue

**Comment by paultcochrane** [comment]
I can confirm that this issue also exists in OL 6.0.0.

**Comment by jonataswalker** [comment]
Published v4.
