### ISSUE TITLE
Submenu items disappear after selecting main menu item on Android as of OL 6.x

### ISSUE THREAD

**Issue by paultcochrane** [jonataswalker/ol-contextmenu#170]
This issue is likely related to #169; at least, I noticed this issue appear after moving from OL 5.x to OL 6.x.

Steps to reproduce this issue:

  - install OL 6.0.0 (or the current version 6.1.1)
  - install ol-contextmenu (current version: 3.3.2)
  - define a context menu with a submenu item, e.g.

```
const contextmenu = new ContextMenu({
  width: 180,
  defaultItems: false,
  items: [
    {
      text: 'Center map here',
      callback: recenterMap,
    },
    '-',
    {
      text: 'Sea-ice concentration',
      items: [
        {
          text: 'Update',
          callback: updateSicData,
        },
      ],
    },
  ],
});
map.addControl(contextmenu);
```

  - load the app in Android (in this particular case bundled as an Android app via Cordova 8.1.2; tested on Android 8.0)
  - ignore the initially shown context menu (the issue mentioned in #169)
  - tap-hold to show the context menu
  - select the menu item with a submenu (in the example here, "Sea-ice concentration")
  - the submenu item appears for a split second and disappears and hence can't be selected

This behaviour doesn't show up in my desktop browser (Firefox 70.0.1; Debian (buster) Linux).  Downgrading the OL version to 5.3.3 (the most recent of the OL 5.x series) fixes the issue (submenu items can be selected), so it seems to be a problem in the interaction between ol-contextmenu and the latest OL version.

Unfortunately, I've no idea how to debug this issue further, however I'd be more than happy to try out any ideas you might have which could solve this problem.

Many thanks for providing this software, it's been very helpful!

**Comment by jonataswalker** [comment]
Probably not (solve this issue) but I'm going to release v4 and wait for you to test against v4.

I'm not sure how to reproduce this in Android, would be a simple browser?

**Comment by paultcochrane** [comment]
Thanks for the release!  It definitely solved issue #169, however the submenu item issue still exists.

I managed to reproduce the issue in Chrome on Android (I couldn't get long-tap to work on Firefox for some reason).  I copied my JS bundle (created via webpack) along with the required css files and the `index.html` file to my Android device (in this case to the `Download` directory and then loaded the `index.html` file in Chrome by explicitly loading `file:///storage/emulated/0/Download/index.html` (opening the file from a file browser didn't work since Chrome does some kind of redirection magic).  After the application loads, a long tap will show the context menu and one can select the submenu, but the submenu item still disappears.

Hope that helps you to find the issue!

**Comment by jonataswalker** [comment]
Sorry, I admit, my feedback has been horrible.

Closing as I have no clue if this is still an issue, please reopen a new one with a repro.

**Comment by paultcochrane** [comment]
Hi @jonataswalker.  No problems!  I believe this issue has been resolved. IIRC my colleague @hw-df at @DriftNoise fixed the issue in a PR, or possibly it was fixed as part of updating ol-contextmenu to a newer version of OpenLayers.  Either way, I'm pretty sure this issue has been resolved.
