### ISSUE TITLE
MousePosition Control displays mouse position while hovering over contextMenu

### ISSUE THREAD

**Issue by tlepkowski** [jonataswalker/ol-contextmenu#174]
This is probably more an issue with ol/control/MousePosition, or controls in general. When I move the mouse, the position changing is displayed even when moving the mouse over context menu.  This can be confusing to users who might select "create Marker Here" widget on the context menu.

**Comment by jonataswalker** [comment]
Sorry, I admit, my feedback has been horrible.

Closing as I have no clue if this is still an issue, please reopen a new one with a repro.
