### ISSUE TITLE
Context menu allows a click on a menu option to propagate to the map

### ISSUE THREAD

**Issue by alex-Hudson** [jonataswalker/ol-contextmenu#176]
Using the context menu it is possible for a click to propagate to the map. 
Whilst I understand this may be desired behaviour in certain situations it would be nice to have the option to disable this behaviour if required.

**Comment by jonataswalker** [comment]
Hi @alex-Hudson 

I'm just waiting for https://github.com/jonataswalker/ol-geocoder/issues/202#issuecomment-565388804
