### ISSUE TITLE
No option to have disabled items on the context menu

### ISSUE THREAD

**Issue by alex-Hudson** [jonataswalker/ol-contextmenu#182]
Hi, 
It would be nice to have a disabled option for items on the context menu so that we can have items that appear but are not selectable (for changing between different modes for example)
Thanks

**Comment by jonataswalker** [comment]
Indeed.

**Comment by jonataswalker** [comment]
Sorry, I admit, my feedback has been horrible.

Closing as I have no clue if this is still an issue, please reopen a new one with a repro.
