### ISSUE TITLE
mobile touch (longtap) event does not works for contextmenu.

### ISSUE THREAD

**Issue by sergmsr** [jonataswalker/ol-contextmenu#189]
Is there any possibility to make contextmenu compatible with mobiles?
Or at least some custom event/method to open menu at specified point of map, so I can handle it by myselft?

**Comment by jonataswalker** [comment]
Hi @sergmsr sorry for this looong delay

PR still opened
https://github.com/jonataswalker/ol-contextmenu/pull/219

I think this is the perfect time to solve this issue.
