### ISSUE TITLE
Creates duplicate callbacks with multiple map instances

### ISSUE THREAD

**Issue by basilmohammed** [jonataswalker/ol-contextmenu#210]
When we have more than one map (even with different map objects),  it creates duplicate callbacks as we have only a single contextmenu object which is global. So when we create a new contextmenu in different map, the contextmenu object gets replaced.

**Comment by jonataswalker** [comment]
Hi @basilmohammed 

I've just published `5.0.0-alpha`. Are you able to help with a validation?

PR still opened
https://github.com/jonataswalker/ol-contextmenu/pull/219

**Comment by basilmohammed** [comment]
Hi @jonataswalker 
Thank you for the update. 
Sorry to say that I am not currently working with this build. 
I am helpless to validate this. 
Really appreciates your effort.

**Comment by rapto** [comment]
I can confirm the bug exists on 5.1.0. In our app, we load an array of maps to show a time evolution of temperature.
