### ISSUE TITLE
Need a @type *.d.ts Dependency File for TypeScript Support

### ISSUE THREAD

**Issue by JubberyXL** [jonataswalker/ol-contextmenu#218]
This OpenLayers control extension currently does not support TypeScript applications and only requires a *.d.ts file to declare the module's dependencies. I see some other people in the issues thread are having the same issues. If you could please add one, I think many people would appreciate it. Thank you

**Comment by jonataswalker** [comment]
Working on a complete rewrite, ok?

Will need some help to validate.

**Comment by JubberyXL** [comment]
Does it need a complete rewrite or just a `ContextMenu.d.ts` file?

**Comment by jonataswalker** [comment]
@JubberyXL I've just published `5.0.0-alpha`. Are you able to help with a validation?

**Comment by JubberyXL** [comment]
@jonataswalker I do not know how much help I can be, but I can take a look
