### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Class constructor Control cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by UglyHobbitFeet** [jonataswalker/ol-contextmenu#220]
Looks like the ol-contextmenu will have to be upgraded to deal with the latest open layers changes for v7

ol v7.0.0
ol-contextMmnu: v4.1.0

TypeError: Class constructor Control cannot be invoked without 'new'
    at new e (ol-contextmenu.js?3d24:6:1)

FWIW ol v6.15.1 did not have this issue

**Comment by jonataswalker** [comment]
I guess this is solved with `5.0.0`, right?
