### ISSUE TITLE
Context Menu not working in various browsers

### ISSUE THREAD

**Issue by thn80** [jonataswalker/ol-contextmenu#227]
Hi,

when trying the examples [Demo](http://rawgit.com/jonataswalker/ol-contextmenu/master/examples/contextmenu.html) or [JSFiddle](https://jsfiddle.net/jonataswalker/ooxs1w5d/) none of them works for me.

What I get is the following:
![menu1b](https://user-images.githubusercontent.com/2078784/191704637-46b23771-eba7-40ca-b4f3-fba2c843d481.jpg)

![menu2b](https://user-images.githubusercontent.com/2078784/191704674-e715c7ea-a651-412a-a2cb-88b9f59fe0d7.jpg)

![menu3b](https://user-images.githubusercontent.com/2078784/191704708-7fb8da2d-56a3-4db9-bdd1-309750c4b7e1.jpg)

Any ideas on how to get it work?

Thanks a lot in advance,

Thomas

**Comment by jonataswalker** [comment]
Hi @thn80 

I forgot to update the fiddle (to use `5.0.0`). Will do it ASAP.

**Comment by jonataswalker** [comment]
Done in `5.0.3`

#228 

Thanks for reporting.
