### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by UglyHobbitFeet** [jonataswalker/ol-contextmenu#229]
Tried v5.0.3 and got

Module not found: Error: Package path ./dist/ol-contextmenu is not exported from package /app/node_modules/ol-contextmenu (see exports field in /app/node_modules/ol-contextmenu/package.json)

The way I am using it in vue is

    <script lang="ts">
      import 'ol-contextmenu/dist/ol-contextmenu.min.css';

Which is the way it was working in v4.1.0

**Comment by UglyHobbitFeet** [comment]
FWIW I've also tried the following with no luck:
import 'ol-contextmenu/dist/ol-contextmenu.css';
import 'ol-contextmenu/ol-contextmenu.css';

**Comment by jonataswalker** [comment]
In the [examples](https://github.com/jonataswalker/ol-contextmenu/blob/master/examples/my-project-with-ol-contextmenu/src/style.css) folder I've used this way:

```css
@import 'ol/ol.css';
@import 'ol-contextmenu/ol-contextmenu.css';
```
Can you try this way for now?

**Comment by jonataswalker** [comment]
I have this code in `package.json`

```json
    "exports": {
        ".": {
            "import": "./dist/ol-contextmenu.js",
            "require": "./dist/ol-contextmenu.umd.cjs",
            "types": "./dist/ol-contextmenu.d.ts"
        },
        "./ol-contextmenu.css": {
            "import": "./dist/ol-contextmenu.css",
            "require": "./dist/ol-contextmenu.css"
        }
    },
```

Not sure what else I have to do.

**Comment by UglyHobbitFeet** [comment]
Using the at symbol gives a parsing error in vue.  So the provided examples do not work. Is there a difference in package.json between the 2 versions which would account for this?

**Comment by jonataswalker** [comment]
`@import` is within your `css` file, right?

**Comment by UglyHobbitFeet** [comment]
No, it is not. It is in a .vue file which compiles the script tag contents.  I don't really have a css file I use but I can create one and try

**Comment by jonataswalker** [comment]
And how about this?

```vue
<template>
  <router-view />
</template>

<style lang="scss">
@import 'ol-contextmenu/ol-contextmenu.css';

body {
  font-family: 'Source Sans Pro', sans-serif;
  background: $white;
  color: #333;
}
</style>
```

**Comment by UglyHobbitFeet** [comment]
I tried adding the @import to a separate css file as I mentioned in an earlier comment.

In order to avoid similar errors I also had to change the Context from
import ContextMenu from 'ol-contextmenu/dist/ol-contextmenu';
to
import ContextMenu from 'ol-contextmenu';

The code now compiles with no errors, however the ContextMenu does not show.  So something is still off about the v5.0.3 over v4.1.0

I will also try with the code blurb you just posted

**Comment by UglyHobbitFeet** [comment]
The style tag you provided results in the same error:
Syntax Error: Error: Package path ./ol-contextmenu.css is not exported from package /app/node_modules/ol-contextmenu (see exports field in /app/node_modules/ol-contextmenu/package.json)

**Comment by jonataswalker** [comment]
Are you able to provide a minimal reproduction?

**Comment by UglyHobbitFeet** [comment]
Unfortunately not, sorry

**Comment by UglyHobbitFeet** [comment]
I took a cursory look at the package.json from v4.1.0 and it looks pretty different than the current one. perhaps the introduction of the exports, modules, types, etc fields are introducing something that is causing the issue, since v4.1.0 works as expected

**Comment by jonataswalker** [comment]
Which bundler are you using?

**Comment by UglyHobbitFeet** [comment]
I'm not sure where to look for that information offhand. Would it be in my
package.json file or an npm/docker command etc

**Comment by UglyHobbitFeet** [comment]
I use the latest vue-cli for vue v2 if that's what you're looking for

**Comment by jonataswalker** [comment]
There's no enough information to continue the investigation.

Generally anyone reporting a problem should provide a reproduction.

**Comment by UglyHobbitFeet** [comment]
I can include a package.json file if that helps but I don't have a project
I can include

**Comment by UglyHobbitFeet** [comment]
A quick vue template would look like:

```
<template>
  <div></div>
</template>
<script lang="ts">
  import Map from 'ol/Map';
  import 'ol-contextmenu/dist/ol-contextmenu.min.css';
  import ContextMenu from 'ol-contextmenu/dist/ol-contextmenu';
  ...
  mounted() {
    const someContextMenuItems = [blah blah];
    const contextMenu = new ContextMenu({
      width: 400,
      defaultItems: true,
      items: someContextMenuItems,
    });
    contextMenu.on('open', (evt) => { ... blah blah});
    this.someMap.addControl(contextMenu);
  }
</script>

```

**Comment by UglyHobbitFeet** [comment]
I came up with a temporary (but undesirable) workaround. I had to manually copy/paste the contents of the css file inline since the import was complaining about the css being private aka not exposed (Syntax Error: Error: Package path ./ol-contextmenu.css is not exported from package /app/node_modules/ol-contextmenu (see exports field in /app/node_modules/ol-contextmenu/package.json))

In my .vue file I have

    <template>
      <div></div>
    </template>
    <script lang="ts">
        import ContextMenu from 'ol-contextmenu';
    </script>
    <style lang="scss">
        .ol-ctx-menu-container{position:absolute; ....
    </style>

**Comment by jonataswalker** [comment]
Sorry, I admit, my feedback has been horrible.

Closing as I have no clue if this is still an issue, please reopen a new one with a repro.

**Comment by UglyHobbitFeet** [comment]
Seems to work fine with vue3 and vite
