### ISSUE TITLE
emitter for ADD_MENU_ENTRY event not being cleaned up

### ISSUE THREAD

**Issue by jcachat** [jonataswalker/ol-contextmenu#236]
I am having an issue that I believe is being caused by the emitter for the ADD_MENU_ENTRY event (which is created in the constructor) not being unregistered.  

My application shows/destroys/re-shows the map many times.  Everything works fine the first time but when the map is destroyed and later re-created, that event is still registered from the first instance.  And I assume, the garbage collector is not freeing it because of references it is holding.  That causes the menu items I set in the 2nd instance to be registered twice and then clicking on them invokes the click event on the menu item twice.  And this process increases each time the map is destroyed and re-created.

I believe the way to fix this would be to register that emitter in setMap when the map is set.  And then add an unregister when setMap is called with null.

**Comment by reza-aslani** [comment]
I'm having the same issue..any solution ?

**Comment by hw-df** [comment]
Can you provide an example which reproduces the problem?

**Comment by jonataswalker** [comment]
@jcachat @reza-aslani 

Are you able to confirm if #238 (published as `v5.1.1`) fixed this issue?

**Comment by phelanHayes** [comment]
I am also experiencing this issue using v5.1.1.  My callbacks for dynamically created items are being called twice.

**Comment by jonataswalker** [comment]
Sorry, I admit, my feedback has been horrible.

Closing as I have no clue if this is still an issue, please reopen a new one with a repro.
