### ISSUE TITLE
Handling padding and window.pageXOffset 

### ISSUE THREAD

**Issue by pelord** [jonataswalker/ol-contextmenu#240]
I try to move from my own method to your project... 

My app handle a sidenav on result, layer TOC and other tool.

When the sidenav is closed, no issue.

But when a open my sidenav, the context menu is offset due to my view padding  (i've clicked on the black cross)

![image](https://user-images.githubusercontent.com/7397743/198861023-8470a4cf-45bc-4cbf-b135-eeca203a5391.png)

I've tried to combine beforeopen  and updateposition.. 
```
  contextmenu.on('beforeopen' as any, function (evt) {
    const pixel = [(evt as any).pixel[0]-400,(evt as any).pixel[1]];
    console.log('here', (evt as any).pixel, pixel);
    contextmenu.updatePosition(pixel);
});
``` 
but I hit a condition that validate if the contextmenu is opened... on update position ...

```
    updatePosition(pixel: Pixel) {
        assert(Array.isArray(pixel), '@param `pixel` should be an Array.');

        if (this.isOpen()) {
            this.pixel = pixel;
            this.positionContainer();
        }
    }
 ``` 
I have also tried with open. But the event is never triggered.  ;(

Do you have any tips for me..
I know it's not a issue.. but i'm looking for some advices. 
On my previous method, I was handling the coord this way.
 ``` 
  private getClickCoordinate(event: { x: number; y: number }) {
    const contextmenuPoint = event;
    const boundingMapBrowser = this.mapBrowser.nativeElement.getBoundingClientRect();
    contextmenuPoint.y =
      contextmenuPoint.y -
      boundingMapBrowser.top +
      (window.scrollY || window.pageYOffset);
    contextmenuPoint.x =
      contextmenuPoint.x -
      boundingMapBrowser.left +
      (window.scrollX || window.pageXOffset);
    const pixel = [contextmenuPoint.x, contextmenuPoint.y];

    const coord = this.map.ol.getCoordinateFromPixel(pixel);
    const proj = this.map.projection;
    return olProj.transform(coord, proj, 'EPSG:4326');
  }

 ``` 
Thanks!

**Comment by jonataswalker** [comment]
Hi there @pelord 

The `open` is back by #238 

Could you try `updatePosition` with `v5.1.1`?

**Comment by jonataswalker** [comment]
@pelord Would you please open a ticket or a PR about the long press?
