### ISSUE TITLE
Uncaught SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by totpero** [jonataswalker/ol-contextmenu#241]
In Mozilla Firefox  console I get this error:
`Uncaught SyntaxError: import declarations may only appear at top level of a module "ol-contextmenu.js:11"`
Using last release [v5.1.0](https://cdn.jsdelivr.net/npm/ol-contextmenu@latest/dist/ol-contextmenu.js) at line 11
This line: `import T from "ol/control/Control";`

**Comment by jonataswalker** [comment]
Hey there @totpero 

Please provide a reproduction.

**Comment by jonataswalker** [comment]
Hopefully solved in `5.2.0` by #260

**Comment by totpero** [comment]
Hi @jonataswalker ,
Yes, this version fix this error.
Thanks 👍

**Comment by jonataswalker** [comment]
I'm not able to help without a reproduction.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by totpero** [comment]
Hi @jonataswalker,
If you try to include https://cdn.jsdelivr.net/npm/ol-contextmenu@latest/dist/ol-contextmenu.js in your project you will get this error in firefox, but I saw in your demo you use ol-contextmenu.iife.js and with this I don't get any error.
