### ISSUE TITLE
Context menu doesn't position correctly

### ISSUE THREAD

**Issue by Saurbaum** [jonataswalker/ol-contextmenu#242]
I attempted to update to the v5.1.0 from v4.1.0

I changed my html to pull in ol-contextmenu.iife.js as it appears ol-contextmenu.js is expecting to be called from a different environment "Cannot use import statement outside a module" when I attempted to use that.

What I see now though is the context menu no longer event attempts to fit into the viewable area and is always appearing high above where I have clicked for it. Emoji is at the point of where the context menu was launched from.

![image](https://user-images.githubusercontent.com/7288848/200886566-800508e3-269e-4529-8e59-8a8720c0f4e9.png)

**Comment by Saurbaum** [comment]
Should I also avoid moving to openLayers 7 for now? In my admittedly brief experiment, it didn't seem compatible.

**Comment by jonataswalker** [comment]
Hey @Saurbaum 

Please, provide a reproduction. Or a fix (haha)?

**Comment by Saurbaum** [comment]
I'll see if I can put a simple reproduction together. It's very unlikely I'll be able to fix it, my javascript skills go as far as plugging one library into the other.

**Comment by jonataswalker** [comment]
Solved by #244
