### ISSUE TITLE
"open" event not triggered when constructed with defaultItems: false

### ISSUE THREAD

**Issue by ahocevar** [jonataswalker/ol-contextmenu#245]
When a context menu is constructed with `defaultItems: false`, the `"open"` event will never be triggered. This is a regression I noticed when updating from the previous major version.

Reproduction case: https://codesandbox.io/s/simple-forked-3z98pn?file=/main.js. When the option is set to `true`, everything works as expected.

**Comment by jonataswalker** [comment]
The `beforeopen` event could be used.

We have this:

`if (this.menuEntries.size === 0) return;`

Not sure if we should change, thoughts?

**Comment by ahocevar** [comment]
I think that `if` check should be removed. It prevents the use of the `open` event the way it is documented, when there are no entries in the context menu yet.

If users are expected to use the `beforeopen` event instead, that should be documented and mentioned in the upgrade notes.

**Comment by iStefo** [comment]
We also encountered this issue when upgrading from an older version. We used beforeopen to check whether to show the menu at all, and open to construct the items, which now doesn‘t work anymore.
While this is not a problem per se, it did cause some efforts debugging this behavior. So maybe at least some warning or so would be much appreciated.

**Comment by jonataswalker** [comment]
@iStefo this one was about the `open` event not being fired when `this.menuEntries.size === 0`. Is your issue solved by removing this condition?

**Comment by ahocevar** [comment]
Thanks, @jonataswalker
