### ISSUE TITLE
When closing the context menu object, the listeners linked to the map are not deleted!

### ISSUE THREAD

**Issue by tmpruler** [jonataswalker/ol-contextmenu#250]
When closing the context menu object, the listeners linked to the map are not deleted.
As a result, if you move from a web page to another page and back, as many listeners as there were transitions are linked to the map. Because of this, when selecting an item in the context menu, the callback function will be called as many times as there were transitions!
So far, to solve the problem, I call the `this.contextmenu.setMap(0) `method, which, if the input argument has the value 0, then the `protected removeListeners()` method is called, which just removes all listeners bound to the map.

**Comment by jonataswalker** [comment]
Couldn't reproduce but the `beforeunload` should be enough.

https://github.com/jonataswalker/ol-contextmenu/pull/257/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR139
