### ISSUE TITLE
Cannot use with parcel

### ISSUE THREAD

**Issue by cwitting** [jonataswalker/ol-contextmenu#252]
When I try to start my server with npm and parcel I get the following error in the console:
`ol-contextmenu.umd.cjs:8 Uncaught TypeError: Class extends value #<Object> is not a constructor or null`

To reproduce:
Put the files I uploaded here [mwe.zip](https://github.com/jonataswalker/ol-contextmenu/files/10536875/mwe.zip) in a folder,
then run:
npm install
npm run start
When accessing the website the error prints to the console.

I think the `import 'ol-contextmenu/dist/ol-contextmenu.css'` line should be `import 'ol-contextmenu/ol-contextmenu.css'` but that also fails with:
`@parcel/core: Failed to resolve 'ol-contextmenu/ol-contextmenu.css' from 
'./main.js'`

**Comment by GastonZalba** [comment]
Parcel doesn't support  the [package.exports](https://github.com/parcel-bundler/parcel/issues/4155) attribute. Try including the file extensions and the entire path:

`import ContextMenu from 'ol-contextmenu/dist/ol-contextmenu.js';`
`import 'ol-contextmenu/dist/ol-contextmenu.css';`

**Comment by cwitting** [comment]
Thanks! Providing the full path works nicely.
