### ISSUE TITLE
Invalid positioning when `push`ing item with sub-items

### ISSUE THREAD

**Issue by iStefo** [jonataswalker/ol-contextmenu#253]
First, thanks for all your effort you put into this library.

After upgrading from 4.1.0 to the latest 5.1.4, I noticed that the context menu gets positioned incorrectly when using `push` to add an item that has a submenu. It seems as if items in the sub menu are counted and used for height calculation of the main menu.

The issue can be reproduced in this fiddle when opening the menu for the second time. Notice the change on line 66: https://jsfiddle.net/7Lgh38af/4/

I will be glad to provide any support, but my own efforts of debugging this issue quickly went dry as I'm not exactly sure what the intended way of counting the items (that are not in any submenu?) are.

The only thing I noticed is that you may have miss-translated the filter condition in `getMenuEntriesLength` if I'm not mistaken (see https://github.com/jonataswalker/ol-contextmenu/blob/4.1.0/src/internal.js#L84 vs. https://github.com/jonataswalker/ol-contextmenu/blob/master/src/main.ts#L317).

**Comment by iStefo** [comment]
Thank you for fixing this, works perfectly now.

**Comment by jonataswalker** [comment]
@iStefo  Thanks for your feedback.
