### ISSUE TITLE
Hi,there,when I use ol-contextmenu4.1.0 in Vue project,the callBack function is not work,I don't how to solove this problem?

### ISSUE THREAD

**Issue by haojingying** [jonataswalker/ol-contextmenu#254]
Hi,there,when I use ol-contextmenu4.1.0 in Vue project,the callBack function is not work,I don't how to solove this problem?

**Comment by jonataswalker** [comment]
Hi @haojingying , are you able to provide a reproduction?

Please .... https://stackoverflow.com/help/minimal-reproducible-example

**Comment by haojingying** [comment]
I have solve this problem,thank you! @jonataswalker
