### ISSUE TITLE
Creates duplicate callbacks with multiple map instances

### ISSUE THREAD

**Issue by phelanHayes** [jonataswalker/ol-contextmenu#261]
Hi @jonataswalker,

We are still experiencing multiple callbacks with menuitems with an application that has multiple maps. We are currently working with ol 7.3.0 and ol-contextmenu 5.2.0.  This doesn't happen on our previous version with ol 6.15.1 and ol-contextmenu 4.1.0.  I will try to put together a repro and am glad to test an -alpha release.

Thank you.             

Hi @basilmohammed 

I've just published `5.0.0-alpha`. Are you able to help with a validation?

PR still opened
https://github.com/jonataswalker/ol-contextmenu/pull/219

_Originally posted by @jonataswalker in https://github.com/jonataswalker/ol-contextmenu/issues/210#issuecomment-1223496115_

**Comment by phelanHayes** [comment]
I haven't been able reproduce in a repro and its possible this is an Angular scoping issue.  If I'm able to reproduce the issue, I'll repost.  Thank you.

**Comment by jonataswalker** [comment]
On it. We are losing the right map reference.

**Comment by basilmohammed** [comment]
@phelanHayes , Checked your repo and confused. For a better clarity, I am suggesting you to create a context menu for any of the map and verify the behavior. Hope my point is clear.

**Comment by phelanHayes** [comment]
Hi @basilmohammed, I'm sure I understand your comment.  In the repro example, there are two maps and two contextmenus, one for each map.  They each have separate event listener functions.  Is this what you mean?  I'm glad to add anything additional that is needed.  

For the repro example, the corresponding event listener fires twice when invoked from its parent map/contextmenu.  Thanks.

**Comment by phelanHayes** [comment]
Thank you @jonataswalker!  I've tested the latest v5.2.1 and the issue is resolved.  Thanks again for all your awesome work.
