### ISSUE TITLE
positioning when extending with sub-items

### ISSUE THREAD

**Issue by phelanHayes** [jonataswalker/ol-contextmenu#266]
Hi @jonataswalker,

Thank you for all your recent work in upgrading the ol-contextmenu to ol7.x.  We are continuing to add functionality within our application that uses the contextmenu.

My request builds upon issue #253 and its fix in PR #258.  PR #258 definitely fixed and adjusted the xy positioning of the contextmenu in relation to pushing extra sub menu items, however the menu isn't minding its parent container as well as it did in version 4.x. with respect to applying 'flip' and xy positioning.

Screenshot depicting behavior with v5.2.1.
<img width="345" alt="olcontextmenu_positioning162623" src="https://github.com/jonataswalker/ol-contextmenu/assets/15438890/7817b8d5-561d-425c-a9a0-2bb7f6ffde9d">

Screenshot depicting behavior with v4.1.0.
<img width="328" alt="image" src="https://github.com/jonataswalker/ol-contextmenu/assets/15438890/5baffe08-7d6f-4219-b0a7-9e1b75519509">

Example Repos:
[ol@7.4.0 with ol-contextmenu@5.2.1](https://codesandbox.io/s/ol-contextmenu-positioning-example-y3ct66?file=/package.json)

[ol@6.15.1 with ol-contextmenu@4.1.0](https://codesandbox.io/s/ol-contextmenu-positioning-example-v4-1-0-jq3vsq?file=/package.json)

**Comment by jonataswalker** [comment]
Hi there @phelanHayes 

Oh Lord, these adjusts seems to be a never ending task 😄 

Are you able to provide a fix?

**Comment by phelanHayes** [comment]
@jonataswalker,

I am glad to investigate and see what I can do.

**Comment by phelanHayes** [comment]
@jonataswalker, by and large I think the positioning is in good shape.  After further working with the source code, I was able to resolve this 'positioning issue with dynamically adding items' by over-riding the 'position' property of the ol-ctx-menu-container class to 'sticky'.  

As always, thank you for your work!
