### ISSUE TITLE
Support for OpenLayers 8

### ISSUE THREAD

**Issue by jakwarrior** [jonataswalker/ol-contextmenu#270]
Is it possible to add support for OpenLayers 8?

**Comment by Zeleksonob** [comment]
waiting for an update as well

**Comment by d-koppenhagen** [comment]
@jonataswalker I saw you merged the PR. Is there a plan to release a new version within the next days?

**Comment by 1Map** [comment]
Yes, I still get 

While resolving: ol-contextmenu@5.2.1
npm ERR! Found: ol@8.1.0
npm ERR! node_modules/ol

**Comment by jonataswalker** [comment]
Done, `5.3.0` published.
