### ISSUE TITLE
OL 9

### ISSUE THREAD

**Issue by 1Map** [jonataswalker/ol-contextmenu#277]
I am using Openlayers 9, but get message like:

 ol-contextmenu@5.3.0" has incorrect peer dependency "ol@> 7.x <= 8.x".

**Comment by jonataswalker** [comment]
If you're in a rush, try this in `package.json`

```json
  "overrides": {
    "ol-contextmenu": {
      "ol": "^9.x"
    }
  }
```
It looks like there's no breaking changes reading their release notes.

**Comment by lucianobazimo** [comment]
Will there be any fix to prevent from this error ?
Thanks :)
