### ISSUE TITLE
Update on OpenLayers 10 Compatibility

### ISSUE THREAD

**Issue by astridx** [jonataswalker/ol-contextmenu#285]
We are using ol-contextmenu on https://tile.openstreetmap.de/. Thank you for your extension!

Locally, we have tested an update to OpenLayers version 10, and everything looked good at first glance. Do you foresee any issues with version 10? Are you planning to update this line: https://github.com/jonataswalker/ol-contextmenu/blob/78906486a9c15fb795cfce911ebfd2cdf913f06c/package.json#L75?

**Comment by jonataswalker** [comment]
Thanks @astridx  for testing against v10. Just published `5.5.0`.
